site_name: Unytics
site_url: https://unytics.io/
theme:
  name: material
  # custom_dir: docs/theme_overrides
  logo: assets/unytics_logo.svg
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    # - instant
    # - toc.integrate
    # - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
plugins: []
